# Default values for log.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imagePullSecrets: ["aliyun"]
elasticsearch:
  name: elasticsearch
  replicas: 2

  image:
    registry: docker.io
    repository: elasticsearch
    tag: 6.4.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    dbPort: 9200
    # dbNodePort: 29200
    transportPort: 9300
    # transportNodePort: 29300
    publishNotReadyAddresses: true
    loadBalancerIP: ""
    externalTrafficPolicy: ""
    loadBalancerSourceRanges: []

  persistence:
    enabled: true
    # existingClaim:
    # storageClass: "-"
    accessModes:
      - ReadWriteMany
    size: 8Gi
    annotations: {}

  cronjob:
    enabled: true
    schedule: "3 1 */1 * *"
    deleteDay: "20"
    deleteIndex: [logs, alpha, zero]

logPilot:
  enabled: true
  name: log-pilot

  image:
    registry: registry.cn-hangzhou.aliyuncs.com
    repository: acs/log-pilot
    tag: 0.9.7-filebeat
    pullPolicy: IfNotPresent

  extraEnvs:
    # 配置ES访问权限
    - name: "ELASTICSEARCH_USER"
      value: ""
    - name: "ELASTICSEARCH_PASSWORD"
      value: ""

logstash:
  enabled: true
  name: logstash
  replicas: 1
  initialProbeDelay: 30

  image:
    registry: docker.io
    repository: logstash
    tag: 6.4.1
    pullPolicy: IfNotPresent

  extraEnvs: []

