kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "log.fullname" . }}-{{ .Values.elasticsearch.name }}
  labels:
    app: {{ include "log.fullname" . }}-{{ .Values.elasticsearch.name }}
    {{- include "log.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "log.fullname" . }}-{{ .Values.elasticsearch.name }}
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "log.fullname" . }}-{{ .Values.elasticsearch.name }}
  apiGroup: ""
