{{- if and .Values.logstash.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "log.fullname" . }}-{{ .Values.logstash.name }}
  labels:
    {{- include "log.selectorLabels" . | nindent 4 }}
    app: {{ include "log.fullname" . }}-{{ .Values.logstash.name }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: input-tcp-port
      protocol: TCP
      name: input-tcp-port
    - port: 5000
      targetPort: input-udp-port
      protocol: UDP
      name: input-udp-port
    - port: 5001
      targetPort: input-http-port
      protocol: TCP
      name: input-http-port

  selector:
    {{- include "log.selectorLabels" . | nindent 4 }}
    app: {{ include "log.fullname" . }}-{{ .Values.logstash.name }}
{{- end }}
