{{- if and .Values.logstash.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "log.fullname" . }}-{{ .Values.logstash.name }}
  labels:
    {{- include "log.selectorLabels" . | nindent 4 }}
    app: {{ include "log.fullname" . }}-{{ .Values.logstash.name }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: input_tcp_port
      protocol: TCP
      name: input_tcp_port
    - port: 5000
      targetPort: input_udp_port
      protocol: TCP
      name: input_udp_port
    - port: 5001
      targetPort: input_http_port
      protocol: TCP
      name: input_http_port

  selector:
    {{- include "log.selectorLabels" . | nindent 4 }}
    app: {{ include "log.fullname" . }}-{{ .Values.logstash.name }}
{{- end }}
